services:
  - type: web
    name: plasticart-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gevent -b 0.0.0.0:$PORT controller:app
    envVars:
      - key: PORT
        value: 10000
